spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/board_db
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update # validate | update | create | create-drop
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 20
        enable_lazy_load_no_trans: true
        format_sql: true
        jdbc:
            lob:
              non_contextual_creation: true